### ISSUE TITLE
Clicking on notification after download complete crashes the demo-simple app

### ISSUE THREAD

**Issue by kaushikmukunda** [novoda/download-manager#142]
1. Open the demo-simple app. 
2. Download the podcast
3. Once the download is finished, click on the "Family of Penguins - Download Complete" notification.

I originally saw this in my app and wanted to check if the demo apps behaved any differently.

```
07-27 09:51:17.268  19439-19614/com.novoda.downloadmanager.demo.simple E/AndroidRuntime﹕ FATAL EXCEPTION: DownloadReceiver
    Process: com.novoda.downloadmanager.demo.simple, PID: 19439
    java.lang.SecurityException: Provider com.novoda.downloadmanager.demo.simple/com.novoda.downloadmanager.lib.DownloadProvider does not allow granting of Uri permissions (uri content://com.novoda.downloadmanager.demo.simple/all_downloads/1)
            at android.os.Parcel.readException(Parcel.java:1465)
            at android.os.Parcel.readException(Parcel.java:1419)
            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2096)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
            at android.app.ContextImpl.startActivity(ContextImpl.java:1047)
            at android.app.ContextImpl.startActivity(ContextImpl.java:1029)
            at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
            at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
            at com.novoda.downloadmanager.lib.DownloadReceiver.openDownload(DownloadReceiver.java:159)
            at com.novoda.downloadmanager.lib.DownloadReceiver.handleNotificationBroadcast(DownloadReceiver.java:108)
            at com.novoda.downloadmanager.lib.DownloadReceiver.access$000(DownloadReceiver.java:31)
            at com.novoda.downloadmanager.lib.DownloadReceiver$1.run(DownloadReceiver.java:92)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by blundell** [comment]
Just looking on github

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadManager.java#L473

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/OpenHelper.java#L44

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/DownloadReceiver.java#L159

is the trace.

When I get a device I'll investigate

**Comment by blundell** [comment]
hmm i just get a toast saying "cannot open file" (not ideal
Xperia Z1c android: 5.0.2

What are you running on?

**Comment by kaushikmukunda** [comment]
I'm running Android 4.4.4 on Nexus 7.
