### ISSUE TITLE
Notification view intent uses android.app.DownloadManager

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#15]
Should use our own ~~(is this why we're getting crashes?)~~ this just doesn't do anything when you click the notification

https://github.com/novoda/download-manager/blob/master/library/src/main/java/com/novoda/downloadmanager/lib/OpenHelper.java#L37

**Comment by blundell** [comment]
ha, nice spot :+1:

**Comment by ouchadam** [comment]
got a crash early with this 

```xml
06-19 15:25:44.199   8591-10158/com.novoda.downloadmanager.demo.serial E/AndroidRuntime﹕ FATAL EXCEPTION: DownloadReceiver
    Process: com.novoda.downloadmanager.demo.serial, PID: 8591
    java.lang.ClassCastException: android.app.DownloadManager cannot be cast to com.novoda.downloadmanager.lib.DownloadManager
            at com.novoda.downloadmanager.lib.OpenHelper.buildViewIntent(OpenHelper.java:37)
            at com.novoda.downloadmanager.lib.DownloadReceiver.openDownload(DownloadReceiver.java:129)
            at com.novoda.downloadmanager.lib.DownloadReceiver.handleNotificationBroadcast(DownloadReceiver.java:94)
            at com.novoda.downloadmanager.lib.DownloadReceiver.access$000(DownloadReceiver.java:30)
            at com.novoda.downloadmanager.lib.DownloadReceiver$1.run(DownloadReceiver.java:80)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```
