### ISSUE TITLE
What unfortunate Authority class is!

### ISSUE THREAD

**Issue by Folyd** [novoda/download-manager#151]
I totally don't understand why there need a `com.novoda.downloadmanager.Authority` class! 

>You also need to create this file in this exact package (we hope to do this for you in the future):

I think it time to do this for us! Look forward!Thanks very much.:)

**Comment by Folyd** [comment]
This is the crash log if i not define a Authority class.

```java
Caused by: java.lang.NullPointerException: com.novoda.downloadmanager.Authority is not defined. See the documentation.
            at com.novoda.downloadmanager.lib.Reflector.throwNoAuthorityClass(Reflector.java:49)
            at com.novoda.downloadmanager.lib.Reflector.reflectAuthority(Reflector.java:24)
            at com.novoda.downloadmanager.lib.DownloadProvider.<clinit>(DownloadProvider.java:64)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.app.ActivityThread.installProvider(ActivityThread.java:4847)
            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4454)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4394)
            at android.app.ActivityThread.access$1500(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by blundell** [comment]
>stupid
>ˈstjuːpɪd/Submit
>adjective
>1.
>lacking intelligence or common sense.

![](http://www.reactiongifs.com/r/2013/07/stupid.gif)
___

It's needed because at the moment the architecture of downloading via this library means we need a static reference to the Authority in use. (the authority determines your database .. you don't want to share a database with someone else do you). It's static because it is needed in a BroadcastReceiver which is started and your application is not guaranteed to be started therefore how else could we request the authority.

https://github.com/novoda/download-manager/blob/840b769023c8e6122c584d823319791a73feb7b5/library/src/main/java/com/novoda/downloadmanager/lib/DownloadProvider.java#L64
