### ISSUE TITLE
Targeting Android O: app crashes when a receiver is called and the app is not running

### ISSUE THREAD

**Issue by cc-rock** [novoda/download-manager#244]
When targeting Android O and running on an O device, if any broadcast receiver gets called when the app is not running (for example the INSTALL_REFERRER receiver), the users sees a crash.
We are currently forced to target api 25 just because of this bug.
The following exception is in the logcat:
```
10-23 11:22:57.993 9540-9540/md.your.lab.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: md.your.lab.debug, PID: 9540
                                                                 java.lang.RuntimeException: Unable to get provider com.novoda.downloadmanager.lib.DownloadProvider: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=md.your.lab.debug/com.novoda.downloadmanager.lib.DownloadService }: app is in background uid UidRecord{6caa78 u0a104 RCVR idle procs:1 seq(0,0,0)}
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=md.your.lab.debug/com.novoda.downloadmanager.lib.DownloadService }: app is in background uid UidRecord{6caa78 u0a104 RCVR idle procs:1 seq(0,0,0)}
                                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                                     at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                                     at com.novoda.downloadmanager.lib.DownloadProvider.onCreate(DownloadProvider.java:302)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
                                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
10-23 11:22:57.993 9540-9540/md.your.lab.debug E/UncaughtException: java.lang.RuntimeException: Unable to get provider com.novoda.downloadmanager.lib.DownloadProvider: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=md.your.lab.debug/com.novoda.downloadmanager.lib.DownloadService }: app is in background uid UidRecord{6caa78 u0a104 RCVR idle procs:1 seq(0,0,0)}
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
                                                                        at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=md.your.lab.debug/com.novoda.downloadmanager.lib.DownloadService }: app is in background uid UidRecord{6caa78 u0a104 RCVR idle procs:1 seq(0,0,0)}
                                                                        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                                        at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                                        at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                                        at com.novoda.downloadmanager.lib.DownloadProvider.onCreate(DownloadProvider.java:302)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
                                                                        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                        at android.os.Looper.loop(Looper.java:164) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by tasomaniac** [comment]
Instead of using `context.startService`, we must use `ContextCompat.startForegroundService` method from support library.

**Comment by Electryc** [comment]
I think this brings back what has been discussed here https://github.com/novoda/download-manager/pull/239 

We need to decide on a strategy in order to enable apps to safely target O. 

cc @joetimmins

**Comment by lwasylkowski** [comment]
@joetimmins @Electryc Sorry for pinging, but are there any plans to support Android O? Developer preview for Android P is out already, and it's a shame we still have to target API <=25.

Maybe you have a rough idea of how would support for O have to be implemented, for potential outside contributors?
