### ISSUE TITLE
Download sometimes fails when pausing

### ISSUE THREAD

**Issue by amlcurran** [novoda/download-manager#61]
This may be the cause of our downloads sometimes failing. Key thing that seems to happen is that it can't delete the file?

``` java
07-03 16:25:44.885    3467-4047/com.novoda.secretz D/NoTils﹕ [DownloadManager-UpdateThread][DownloadDeleter.deleteFileIfExists:64] deleteFileIfExists() deleting /data/data/com.novoda.secretz/files/60545.tmp
07-03 16:25:45.778    3467-4051/com.novoda.secretz W/NoTils﹕ [pool-7-thread-1][Log.w:99] Aborting request for download 2: download canceled
    com.novoda.downloadmanager.lib.StopRequestException: download canceled
            at com.novoda.downloadmanager.lib.DownloadThread.checkPausedOrCanceled(DownloadThread.java:541)
            at com.novoda.downloadmanager.lib.DownloadThread.transferData(DownloadThread.java:500)
            at com.novoda.downloadmanager.lib.DownloadThread.transferData(DownloadThread.java:427)
            at com.novoda.downloadmanager.lib.DownloadThread.executeDownload(DownloadThread.java:348)
            at com.novoda.downloadmanager.lib.DownloadThread.runInternal(DownloadThread.java:244)
            at com.novoda.downloadmanager.lib.DownloadThread.run(DownloadThread.java:174)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
07-03 16:25:45.779    3467-4051/com.novoda.secretz D/NoTils﹕ [pool-7-thread-1][DownloadThread.cleanupDestination:522] cleanupDestination() deleting /data/data/com.novoda.secretz/files/60545.tmp
07-03 16:25:45.779    3467-4051/com.novoda.secretz E/NoTils﹕ [pool-7-thread-1][DownloadThread.cleanupDestination:525] File not deleted
07-03 16:25:46.028    3467-4051/com.novoda.secretz I/NoTils﹕ [pool-7-thread-1][DownloadThread.runInternal:295] Download 2 finished with status CANCELED
```

**Comment by blundell** [comment]
So you mean you press the button to pause it but then it is cancelled instead?

**Comment by amlcurran** [comment]
Yeah, Xavi and I think that the file gets in some inconsistent state so it cannot resume

**Comment by xrigau** [comment]
does this still happen?
